import type { SimpleIcon } from 'simple-icons'
import {
  siAngular,
  siApache,
  siCpanel,
  siCss,
  siDocker,
  siExpress,
  siFastapi,
  siFilezilla,
  siGit,
  siGithub,
  siHtml5,
  siIonic,
  siJavascript,
  siJsonwebtokens,
  siLaravel,
  siLetsencrypt,
  siLinux,
  siMongodb,
  siMysql,
  siNginx,
  siNodedotjs,
  siOpencv,
  siPhp,
  siPostgresql,
  siPython,
  siReact,
  siSocketdotio,
  siSupabase,
  siTailwindcss,
  siTensorflow,
  siTypescript,
  siUltralytics,
  siVite,
} from 'simple-icons'

export const TECH_ICONS: Record<string, SimpleIcon> = {
  PHP: siPhp,
  Laravel: siLaravel,
  cPanel: siCpanel,
  'Node.js': siNodedotjs,
  TypeScript: siTypescript,
  JavaScript: siJavascript,
  Express: siExpress,
  WebSockets: siSocketdotio,
  Python: siPython,
  FastAPI: siFastapi,
  YOLO: siUltralytics,
  OpenCV: siOpencv,
  TensorFlow: siTensorflow,
  React: siReact,
  Angular: siAngular,
  Ionic: siIonic,
  Vite: siVite,
  'Tailwind CSS': siTailwindcss,
  'HTML/CSS': siHtml5,
  CSS: siCss,
  PostgreSQL: siPostgresql,
  MySQL: siMysql,
  MongoDB: siMongodb,
  Supabase: siSupabase,
  Docker: siDocker,
  Git: siGit,
  GitHub: siGithub,
  Linux: siLinux,
  Nginx: siNginx,
  Apache: siApache,
  FTP: siFilezilla,
  'SSL/TLS': siLetsencrypt,
  'Auth (JWT/OAuth)': siJsonwebtokens,
}

export function hasTechIcon(name: string) {
  return name in TECH_ICONS
}
